### PR TITLE
Add flake support

### PR DESCRIPTION
**Pull request by Ruixi-rebirth**
#### Format
- *.sh is formatted by *beautysh* and has an indent size of *4* spaces
- *.yaml, *.md formatted by *prettier*
- *.toml is formatted by *taplo*
- *.rs formatted by *rustfmt*
#### Add flake support
- Provide development environment
- Provision of all file types within the format project
- Provides nixos with a way to install the git version of this package

https://github.com/kamiyaa/joshuto/assets/75824585/46bbe755-5404-4b20-95d0-b78966278e15

### CODE REVIEW

**Comment by Ruixi-rebirth** [comment]
@kamiyaa

**Comment by kamiyaa** [comment]
The style changes is all good, but does the NixOS Flake support have to be part of the main codebase?

I ask this because usually package files are stored and maintained by the OS repositories rather than the program.
ie. pkgbuilds for arch, ebuilds for gentoo, rpm for fedora, deb for debian.

**Comment by Ruixi-rebirth** [comment]
Yes, it has to be part of the main code. Although nixos upstream has already been packaged, it makes the most sense to enable flake support for this repository in order to update it at the same time as this one

**Comment by Ruixi-rebirth** [comment]
There are also other repositories with flake support, these are examples: [wayabr](https://github.com/Alexays/Waybar) [leftwm](https://github.com/leftwm/leftwm) [hyprland](https://github.com/hyprwm/Hyprland) [pianotrans](https://github.com/azuwis/pianotrans) ......

**Comment by kamiyaa** [comment]
> Yes, it has to be part of the main codebase. Although nixos upstream has already been packaged, it makes the most sense for users to enable flake support for this repository in order to update it at the same time as this one

Got it!

**Review by kamiyaa — APPROVED** [review]

**Pull request merged**
