### PR TITLE
Added `rename_keep_ext` command and refactored rename functions

### PR DESCRIPTION
**Pull request by fritzrehde**
Added the `rename_keep_ext` command as discussed in #214.
Refactoring: removed unnecessary code duplication with helper function `_get_current_file_name` and added some match statements for cleaner code (e.g. a `None => {}` more clearly indicates that nothing should be done in that case).

### CODE REVIEW

**Comment by kamiyaa** [comment]
You will need to update `impl_from_str.rs` as well so `joshuto` will know how to read the config file

**Comment by fritzrehde** [comment]
I did update `impl_from_str.rs` and when testing it with a config containing `rename_keep_ext` it worked as expected.

**Comment by fritzrehde** [comment]
> Added the `rename_keep_ext` command as discussed in #214. Refactoring: removed unnecessary code duplication with helper function `_get_current_file_name` and added some match statements for cleaner code (e.g. a `None => {}` more clearly indicates that nothing should be done in that case).

So clippy isn't happy with the exact change I made to the match statements, I'll try to fix that.

**Comment by kamiyaa** [comment]
> > Added the `rename_keep_ext` command as discussed in #214. Refactoring: removed unnecessary code duplication with helper function `_get_current_file_name` and added some match statements for cleaner code (e.g. a `None => {}` more clearly indicates that nothing should be done in that case).
> 
> So clippy isn't happy with the change I made to the match statements, I'll try to fix that. I tried running `cargo clippy` on my local joshuto repo, but it gave me thousands of lines of seemingly unrelated errors like:
> 
> ```
> error[E0514]: found crate `tui` compiled by an incompatible version of rustc
>  --> src/ui/widgets/tui_footer.rs:4:5
>   |
> 4 | use tui::text::{Span, Spans};
>   |     ^^^
>   |
>   = help: please recompile that crate using this compiler (rustc 1.64.0 (a55dd71d5 2022-09-19)) (consider running `cargo clean` first)
>   = note: the following crate versions were found:
>           crate `tui` compiled by rustc 1.64.0 (Arch Linux rust 1:1.64.0-1): /home/fritz/code/joshuto/target/debug/deps/libtui-c53553651fa70c9d.rmeta
> 
> error[E0514]: found crate `tui` compiled by an incompatible version of rustc
>  --> src/ui/widgets/tui_footer.rs:5:5
>   |
> 5 | use tui::widgets::{Paragraph, Widget};
>   |     ^^^
>   |
>   = help: please recompile that crate using this compiler (rustc 1.64.0 (a55dd71d5 2022-09-19)) (consider running `cargo clean` first)
>   = note: the following crate versions were found:
>           crate `tui` compiled by rustc 1.64.0 (Arch Linux rust 1:1.64.0-1): /home/fritz/code/joshuto/target/debug/deps/libtui-c53553651fa70c9d.rmeta
> ```
> 
> Does anyone know how to only show the errors also shown in the github CI?

You can look at the commands github action runs: https://github.com/kamiyaa/joshuto/actions/runs/3330346550/workflow#L25

**Comment by fritzrehde** [comment]
I think everything is fixed now.

**Review by kamiyaa — APPROVED** [review]
LGTM!

**Pull request merged**
