### PR TITLE
Added basic implementation of devicons

### PR DESCRIPTION
**Pull request by SaeedAnas**
I have wrote a basic implementation for devicons support for file and directory names, which is requested in #3. Ported the dictionaries from [ranger devicons](https://github.com/alexanderjeurissen/ranger_devicons) into static hashmaps using the [rust phf crate](https://github.com/sfackler/rust-phf), and added configuration for showing the icons.

### CODE REVIEW

**Comment by kamiyaa** [comment]
Hey, this is awesome! Great work! :heart: 

There is one thing I would like to point out so far.
Because the icon is part of the name now, sorting is not working as intended.
We will need to change the way `util/sort.rs` works so it doesn't work off of `direntry.file_name()` because that will give the name with the devicons :+1:

**Comment by SaeedAnas** [comment]
To address the sorting bug, i've changed ```direntry.file_name()``` to ```direntry.raw_file_name()``` in ```sort::compare()```. Would any other modules also require this change, such as the renaming logic?

**Comment by kamiyaa** [comment]
> Would any other modules also require this change, such as the renaming logic?

Yep! Good eye

**Comment by SaeedAnas** [comment]
Instead of having to change all modules that need to use ```direntry.file_name()```, I thought it would be better to change the modules that will be rendering the filename, so i modified ```tui_dirlist``` and ```tui_dirlist_detailed``` to use ```direntry.label()```, which contains the icon and the filename. Would this be sufficient?

**Comment by kamiyaa** [comment]
Looks good to me!

**Pull request merged**
