### PR TITLE
Make mouse support configurable

### PR DESCRIPTION
**Pull request by Mroik**
Implements request of issue #402 for mouse support to be configurable through `joshuto.toml` instead of it being a cargo feature.

### CODE REVIEW

**Review by kamiyaa — COMMENTED** [review]
Ideally I would like turning off mouse support to be able to select text.
As it is, when mouse is enabled or disabled, text cannot be selected via mouse.

So some programmatic way to use MouseTerminal

**Comment by Mroik** [comment]
I really dislike this solution, made me change the signature of some functions to pass `context`. I don't think this is avoidable due to the fact that `Screen` was an alias had different types based on the `cargo features`.

**Comment by kamiyaa** [comment]
> I really dislike this solution, made me change the signature of some functions to pass `context`. I don't think this is avoidable due to the fact that `Screen` was an alias had different types based on the `cargo features`.

An alternative solution could be to keep the mouse feature, have it enabled by default and can be changed via config (the work you did).
What do you think?

**Comment by Mroik** [comment]
> An alternative solution could be to keep the mouse feature, have it enabled by default and can be changed via config (the work you did).

Not sure what you mean, as it is right now in this branch it is done only through the config (there wouldn't be a need for a cargo feature).
What I was referring to is [this](https://github.com/kamiyaa/joshuto/pull/494/commits/e48815d1d3b015f361ff1399e1c2be6f0785cb6f#diff-fe75a4d3e38caa85ca749984438fd437d8f87bfca931c0e6e3e330d744f72bf3R17). I don't think we can avoid an enum given that the previous implementation for the mouse support toggle via cargo feature achieved it through different types.

**Comment by Mroik** [comment]
Not sure if I explained myself, sorry if I wasn't too clear :sweat_smile:

**Comment by kamiyaa** [comment]
Okay, this is fine. I am content with this haha.

**Comment by kamiyaa** [comment]
Thanks!

**Pull request merged**
