### PR TITLE
feat: Add mouse scrolling in file preview

### LINKED ISSUE #535: Feature request: implement scrollable preview area
It's amazing joshuto has `mouse_support = true` thank you so much for adding it.

If it also suppored scrolling the preview same as ranger I would definitely use it for my daily work.

### PR DESCRIPTION
**Pull request by krivahtoo**
- Add file preview scrolling with the mouse.
- Limit file preview scrolling to the last 3 lines to avoid scrolling way past the last line of the file.

Closes #535

### CODE REVIEW

**Comment by Zeioth** [comment]
Looks good. Video comparison here:
https://www.youtube.com/watch?v=CjKcNoJ9VF4

Left: ranger
Right: joshuto

**Comment by krivahtoo** [comment]
> Looks good. Video comparison here: https://www.youtube.com/watch?v=CjKcNoJ9VF4
> 
> Left: ranger Right: joshuto

Is joshuto scroll speed too fast or ranger is just too slow? 🤔

**Comment by Zeioth** [comment]
Yes ranger scrolls slower (a bit too much).

**Review by kamiyaa — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
