### PR TITLE
use cli-clipboard for path copy

### PR DESCRIPTION
**Pull request by ztlevi**
Hi, 

I have xclip installed on my MacOS and it hangs during path copy. Use the clipboard library for better cross platform support.

### CODE REVIEW

**Comment by ztlevi** [comment]
Tested on my mac but haven't tested on Linux since the dockerfile doesn't seem to work.

**Comment by kamiyaa** [comment]
I would like to avoid bringing in dependencies like cli-clipboard because it introduces dependencies for x11 and wayland libraries on Linux. Ie. Joshuto will fail to compile if either is missing.

Instead, I would like to keep the approach of using cli commands to copy things to clipboard.

If the existing code does not work for Mac, you can add a Mac specific command when compiling for Mac.

Let me know if you have any questions!

**Comment by ztlevi** [comment]
Got it. I don't feel like cli-clipboard needs additionaly linux library while [rust-clipboard](https://github.com/aweinstock314/rust-clipboard) did mention xorg-dev needs to be installed.

But based on your concern, I added `pbcopy` command to support MacOS clipboard. pbcopy comes with mac by default

**Comment by kamiyaa** [comment]
LGTM! Thanks!

**Pull request merged**
