### PR TITLE
Add tilde_in_titlebar option

### PR DESCRIPTION
**Pull request by cjbassi**

### CODE REVIEW

**Comment by cjbassi** [comment]
Fixed merge conflicts.

**Comment by cjbassi** [comment]
Also, should we use the same setting names in joshuto as in ranger, or not really? Cause in ranger, this option is called `tilde_in_titlebar`.

**Comment by kamiyaa** [comment]
Nah it's okay. Even though this is like a ranger clone, I don't really intend on keeping backwards compatibility or anything. I am just busy with school currently.

**Comment by kamiyaa** [comment]
Thanks!

**Pull request merged**
