### PR TITLE
Added custom_commands and custom_search

### PR DESCRIPTION
**Pull request by Dzordzu**
Implemented #338

### CODE REVIEW

**Comment by Dzordzu** [comment]
Demo:
joshuto_demo

**Comment by Dzordzu** [comment]
@kamiyaa can you look at it?

**Comment by kamiyaa** [comment]
> @kamiyaa can you look at it?

Yep! Sorry, I've just been busy :x

**Comment by kamiyaa** [comment]
Looks good so far.

Is there a reason for putting it inside `joshuto.toml`?
I think it would make more sense to keep inside `keymap.toml`
But on the other hand, that might make `keymap.toml` more complicated than it needs to be

Also, if you could add documentation for the new commands inside `docs/` either in this PR, or a followup PR, that would be great!

**Comment by Dzordzu** [comment]
> Is there a reason for putting it inside `joshuto.tom`l

Yep. It may be later used as the simple plugin system (not only for commands, but for example for another window)

> I think it would make more sense to keep inside `keymap.toml`

I also thought about it, but it is not a keymap, but a more general component

> But on the other hand, that might make `keymap.toml` more complicated than it needs to be

Yep

> Also, if you could add documentation for the new commands inside `docs/ `

Oh. I forgot to include it! I will create a commit with docs in the following days :)

**Comment by Beethoven-n** [comment]
what're we waiting for? everything looks good from here

**Comment by Dzordzu** [comment]
I need to resolve conflicts, add more documentation. Furthermore I'm required to find a spare time and will to contribute (a little personal issues, sorry for that!)

**Comment by kamiyaa** [comment]
Just ping me when its ready!

**Comment by Dzordzu** [comment]
I messed it so badly, that I needed to open another PR. Working at nights is really funny!

**Pull request closed without merging**
